import type { Metadata } from 'next';
import '../styles/globals.css';
import ModalProvider from '@/contexts/ModalContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body
        className={'h-dvh w-screen content-center bg-[#ECECEC]'}
      >
      <ModalProvider>
        <main className='relative mx-auto flex h-full max-h-dvh w-full min-w-[360px] max-w-[430px] flex-col bg-white'>
          {children}
          <div id="modal"/>
        </main>
      </ModalProvider>
      </body>
    </html>
  );
}