version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: chat-mysql
    environment:
      MYSQL_DATABASE: chat_service
      MYSQL_USER: chat_service_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
    ports:
      - "3309:3306"
    command:
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
      --default-time-zone=Asia/Seoul
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  backend-1:
    build:
      context: .
      dockerfile: DockerFile
    container_name: chat-backend-1
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  backend-2:
    build:
      context: .
      dockerfile: DockerFile
    container_name: chat-backend-2
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: nginx:latest
    container_name: chat-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2