version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: chat-mysql
    environment:
      MYSQL_DATABASE: chat_service
      MYSQL_USER: chat_service_user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: chat-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started