spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/chat_service
    username: chat_service_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

oauth:
  kakao:
    client-id: f02067b7efddad059ef95b78b3f072e6
    redirect-uri: http://localhost:8080/auth/login/kakao
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
  secret: 45eeHf/MQY5Fh6nkeDIR10OFtlgd3mwPIzxFhvpaLvsiPJFtBq+t/Sc0icBsHKDnRKZJysgXO0b7RRV1urz7Iw==
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG